"""empty message

Revision ID: 0e51c0be31c7
Revises: c34412697eca
Create Date: 2023-12-01 03:36:58.302651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e51c0be31c7'
down_revision = 'c34412697eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('prompt', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prompt'], ['prompt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response', sa.Integer(), nullable=True))
        batch_op.drop_constraint('sample_prompt_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'response', ['response'], ['id'])
        batch_op.drop_column('prompt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prompt', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('sample_prompt_fkey', 'prompt', ['prompt'], ['id'])
        batch_op.drop_column('response')

    op.drop_table('response')
    # ### end Alembic commands ###
