"""empty message

Revision ID: 2ba102fe2918
Revises: d8893e2b0dc6
Create Date: 2023-12-01 02:21:13.844805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ba102fe2918'
down_revision = 'd8893e2b0dc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.String(length=100), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question')
    )
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index('question_index', ['question'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_index('question_index')

    op.drop_table('question')
    # ### end Alembic commands ###
