"""empty message

Revision ID: 3f21ecf7cd9c
Revises: 7c17c294c64a
Create Date: 2023-11-30 02:17:53.704857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f21ecf7cd9c'
down_revision = '7c17c294c64a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.drop_index('task_id')
        batch_op.create_index('task_id', ['task_id'], unique=False)
        batch_op.create_index('problem', ['problem'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.drop_index('problem')
        batch_op.drop_index('task_id')
        batch_op.create_index('task_id', ['task_id'], unique=False)

    # ### end Alembic commands ###
