"""empty message

Revision ID: 67669753d045
Revises: b8df1d65b38a
Create Date: 2023-12-01 08:53:47.871252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67669753d045'
down_revision = 'b8df1d65b38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mark', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.drop_column('mark')

    # ### end Alembic commands ###
