"""empty message

Revision ID: 99ff344ce92f
Revises: 2ba102fe2918
Create Date: 2023-12-01 02:55:38.221917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ff344ce92f'
down_revision = '2ba102fe2918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prompt')
    )
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.create_index('prompt_index', ['prompt'], unique=False)

    op.create_table('sample',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.Column('prompt', sa.Integer(), nullable=True),
    sa.Column('answer', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['prompt'], ['prompt.id'], ),
    sa.ForeignKeyConstraint(['question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample')
    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.drop_index('prompt_index')

    op.drop_table('prompt')
    # ### end Alembic commands ###
