"""empty message

Revision ID: b53d18904fc3
Revises: 8f1c61c7b3c8
Create Date: 2023-11-30 03:03:42.047611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b53d18904fc3'
down_revision = '8f1c61c7b3c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.create_index('problem', ['problem'], unique=False)
        batch_op.create_index('task_id', ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.drop_index('task_id')
        batch_op.drop_index('problem')

    # ### end Alembic commands ###
