"""empty message

Revision ID: b8df1d65b38a
Revises: 484aeda95eaf
Create Date: 2023-12-01 08:11:30.736952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8df1d65b38a'
down_revision = '484aeda95eaf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.drop_constraint('html_task_id_problem_key', type_='unique')
        batch_op.drop_index('problem')
        batch_op.drop_index('task_id')
        batch_op.drop_column('task_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_id', sa.VARCHAR(length=96), autoincrement=False, nullable=True))
        batch_op.create_index('task_id', ['task_id'], unique=False)
        batch_op.create_index('problem', ['problem'], unique=False)
        batch_op.create_unique_constraint('html_task_id_problem_key', ['task_id', 'problem'])

    # ### end Alembic commands ###
