"""empty message

Revision ID: e8c3978e8e88
Revises: 67669753d045
Create Date: 2023-12-01 21:35:30.753425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8c3978e8e88'
down_revision = '67669753d045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.String(length=32), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('response_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sample')
    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.alter_column('problem',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('mark',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('instruction',
               existing_type=sa.TEXT(),
               nullable=False)

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('prompt_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.alter_column('prompt_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('response',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.alter_column('instruction',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('question',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('prompt', schema=None) as batch_op:
        batch_op.alter_column('prompt',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('html', schema=None) as batch_op:
        batch_op.alter_column('mark',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('problem',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.create_table('sample',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('answer', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='sample_question_id_fkey'),
    sa.ForeignKeyConstraint(['response_id'], ['response.id'], name='sample_response_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='sample_pkey')
    )
    op.drop_table('answer')
    # ### end Alembic commands ###
